# Generated by Django 4.2.6 on 2023-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_id_alter_conversationmessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat/photos/'),
        ),
    ]
