# Generated by Django 4.2.6 on 2023-11-03 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
