# Generated by Django 4.2.6 on 2023-11-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_repost_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
