# Generated by Django 4.2.6 on 2023-11-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_delete_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to=settings.AUTH_USER_MODEL)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='post.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='reposted_by',
            field=models.ManyToManyField(blank=True, to='post.repost'),
        ),
    ]
