# Generated by Django 4.2.6 on 2023-11-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_reposts_count_repost_post_reposted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repost',
            options={'ordering': ('-created_at',)},
        ),
    ]
