# Generated by Django 4.2.6 on 2023-12-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_repost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/videos/'),
        ),
    ]
