# Generated by Django 4.2.6 on 2023-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_postattachment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_attachments/images/'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/videos/'),
        ),
    ]
