# Generated by Django 4.2.6 on 2023-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_postattachment_file_postattachment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postattachment',
            name='video',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/file/'),
        ),
    ]
